### ISSUE TITLE
Donation: @jcadduono

### ISSUE THREAD

**Issue by kimocoder** [offensive-security/nethunter-devices#183]
I may send you a OnePlus 6 with 256gb and 8gb memory if you need a A/B device. It's pretty quick too, and battery lasts,

Send me an email at christian -at- aircrack.... you now the rest and I'll ship it your way.
Cheers

**Comment by jcadduono** [comment]
I don't know, I'm so busy with other things in life that I fear if I accept this I will be too obligated to work on NetHunter again.
Truth be told, I am not sure my WoW addiction will let me work on this.

**Comment by SymbianSyMoh** [comment]
@kimocoder @jcadduono 

What about this one: https://github.com/johanlike/Oneplus6-or-6T-Nethunter-Kernel

It might help, the author tested it already on 6 and 6T!

I guess if he made a PR would help to be added here!

**Comment by kimocoder** [comment]
@SymbianSyMoh I know that feeling, James!

@johanlike kernel make my OnePlus 6 crash hard every time. The source uploaded to GitHub is also all in 1 upload.. so we don't really see (or learn) by it for that means...

What he should do? Fork the "nethunter-devices" himself and start integration, but for now.. my OnePlus 6 says pass on that kernel. Several issues, files created random and bootloops and missing kernel modules even when following README-EN.md

He should make the PR itself, but for us others.. we like to see what has been done to the kernel and not and maybe even jumo into it.

@jcadduono You and @binkybear @Re4son has done so much.. You did it all really, with some help from the community, but me and @Re4son still got some spare time left :1st_place_medal: 

Cheers boss!

**Comment by kimocoder** [comment]
You find me at christian - a - aircrack-ng.org if there's anything, sir.

**Comment by SymbianSyMoh** [comment]
@kimocoder Didn't understood what you mean :D

**Comment by johanlike** [comment]
Hi@kimocoder  
Sorry, my English is not very good, so I have been using Google Translate. I may not clearly express what I want in the README-EN.md instructions. Are you currently experiencing a phone crash? Or do you want to push the kernel to the nethunter-devices master?? If the phone crashes frequently and restarts, you need to roll back the ROM version to OOS BETA 1-5 or the official stable version (all versions passed my test). You want me to push the kernel to "nethunter-devices master", I think I need help, because I am a github rookie. I don't understand how to operate.
I am currently debugging the kernel to support OOS BETA 6-7, which may take some time.
If you need help, you can join my telegraph team because I often check the telegraph team's information.

**Comment by johanlike** [comment]
@kimocoder @SymbianSyMoh 
In addition, I also purchased the 8814AU, which may arrive in the next few days. I may add 8814AU driver support in the follow-up. Thank you for your attention.
